title: Aditya Dindi's Blog
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#008"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: https://github.githubassets.com/images/icons/emoji/octocat.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://adityadindi.com/
  zip_title: Portfolio Website
  zip_hide: false
  tar_hide: true
  github_hide: true