title: Aditya Dindi's Blog
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#FFFFFF"
  gradient_left: "#8BC34A"
  gradient_right: "#388E3C"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://adityadindi.com/
  zip_title: Portfolio Website
  zip_hide: false
  tar_hide: true
  github_hide: true